name: macroeco_phylo
channels:
  - etetoolkit
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - argtable2=2.13=0
  - ca-certificates=2022.6.15=h033912b_0
  - certifi=2021.5.30=py36h79c6626_0
  - clustalo=1.2.4=h8fd5eaf_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.24=py36hefe7e0e_0
  - dbus=1.13.6=h811a1a6_3
  - dialigntx=1.0.2=h9803431_0
  - ete3=3.1.2=pyh39e3cac_0
  - ete_toolchain=3.0.0=h73706c9_0
  - expat=2.4.8=h96cf925_0
  - fasttree=2.1.11=hdcdfbac_1
  - freetype=2.10.4=h4cff582_1
  - gettext=0.19.8.1=hd1a6beb_1008
  - icu=58.2=h0a44026_1000
  - iqtree=1.5.5=h8fdce63_0
  - jpeg=9e=h5eb16cf_1
  - kalign=2.03=hf9ccdb1_0
  - kiwisolver=1.3.1=py36hc61eee1_1
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=15_osx64_openblas
  - libcblas=3.9.0=15_osx64_openblas
  - libcxx=14.0.5=hce7ea42_1
  - libdeflate=1.10=h0d85af4_0
  - libffi=3.4.2=h0d85af4_5
  - libgcc=4.8.5=1
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.70.2=hf1fb8c0_4
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=15_osx64_openblas
  - libopenblas=0.3.20=openmp_hb3cd9ec_0
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.3.0=hfca7e8f_4
  - libwebp-base=1.2.2=h0d85af4_1
  - libxml2=2.9.14=hbf8cd5e_0
  - libxslt=1.1.35=h5b33f42_0
  - libzlib=1.2.12=hfe4f2af_1
  - llvm-openmp=14.0.4=ha654fa7_0
  - lxml=3.8.0=py36_0
  - lz4-c=1.9.3=he49afe7_1
  - mafft=6.861=h419a82f_0
  - matplotlib=3.3.4=py36h79c6626_0
  - matplotlib-base=3.3.4=py36h4ea959b_0
  - mpmath=1.2.1=pyhd8ed1ab_0
  - muscle=3.8.31=hcb68c7d_0
  - ncurses=6.3=h96cf925_1
  - numpy=1.19.5=py36h08b5fde_2
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1q=hfe4f2af_0
  - paml=4.8=hace986f_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - phylobayes=4.1c=hf7d3357_0
  - phyml=20160115.patched=h98c79a7_0
  - pillow=8.3.2=py36h950f3bb_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pmodeltest=1.4=py36h1cf33f0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.9.2=py36h2a560b1_4
  - python=3.6.15=haf480d7_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2022.1=pyhd8ed1ab_0
  - qt=5.9.7=h93ee506_2
  - raxml=8.2.11=hab3343f_0
  - readline=8.1.2=h3899abd_0
  - scipy=1.5.3=py36h4f136de_1
  - setuptools=49.6.0=py36h79c6626_3
  - sip=4.19.8=py36h0a44026_0
  - six=1.16.0=pyh6c4a22f_0
  - slr=1.4.3=h3de9e2b_0
  - sqlite=3.38.5=hd9f0692_0
  - statsmodels=0.9.0=py36h917ab60_1000
  - sympy=1.5.1=py36h9f0ad1d_2
  - t_coffee=11.00=h5f19bac_0
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.1=py36hfa26744_1
  - trimal=1.4=h2778685_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.12=hfe4f2af_1
  - zstd=1.5.2=ha9df2e0_1
  - pip:
    - biom-format==2.1.12
    - cached-property==1.5.2
    - click==8.0.4
    - h5py==3.1.0
    - importlib-metadata==4.8.3
    - pandas==1.1.5
    - typing-extensions==4.1.1
    - zipp==3.6.0
prefix: /opt/anaconda3/envs/macroeco_phylo
